apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: hospital-app
  name: hospital-app
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: hospital-app
status:
  loadBalancer: {}
